# Generated by Django 2.2.16 on 2023-03-21 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20230218_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('title',), 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Добавьте полное описание группы, чтобы вам было проще найти единомышленников.', verbose_name='Описание группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'Группа с таким идентификатором уже существует.'}, help_text='Введите идентификатор, который будет частью URL страницы. Допустимо использование латинских букв, символ тире и нижнее подчёркивание.', unique=True, verbose_name='Уникальный идентификатор группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(error_messages={'max_lenght': 'Название группы не должно превышать 200 символов.', 'unique': 'Группа с таким названием уже существует.'}, help_text='Введите название группы.', max_length=200, unique=True, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа, к которой будет относиться пост', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Group', verbose_name='Группа публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Текст нового поста', verbose_name='Текст публикации'),
        ),
    ]
